export const message = {
  EMAIL_FORMAT: "Email has must have correct format",
  WARNING_PERMISSION: "You do not have permission go to this page!",
  SOME_HAPPEN: "Some error happened!",
  AVT_UPLOAD_SUCCESS: "Avatar updated successful",
  AVT_UPLOAD_FAILED: "Avatar updating failed",
  NAME_LEAST: "Name must be at least 5 characters",
  NAME_LESS: "Name must be less than 12 characters",
  USERNAME_SUCCESS: "Username updated successful",
  USERNAME_FAILED: "Username updating failed",
  CONFIRM_PASSWORD: "Confirm password is incorrect",
  PASSWORD_LEAST: "Password must be at least 8 characters.",
  PASSWORD_UPDATE: "Password has been updated.",
  REGISTER_SUCCESS: "Register Hrm Successfully",
  REGISTER_FAILED: "Register Hrm Failed",
};
